using System.Web;
using System.Web.Mvc;

namespace PandaWeb
{
    
    //Specifies what to do with execeptions generated by action-methods. This is the default setting.
    public class FilterConfig
    {
        public static void RegisterGlobalFilters(GlobalFilterCollection filters)
        {
            filters.Add(new HandleErrorAttribute());
        }
    }
}
